import { readFileSync, writeFileSync } from "fs";
import { join, resolve } from "path";

const root = resolve();
const version = JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version;

// Cargo.toml
const cargoPath = join(root, "src-tauri/Cargo.toml");
let cargo = readFileSync(cargoPath, "utf8");
cargo = cargo.replace(/^(version\s*=\s*)"[^"]*"/m, `$1"${version}"`);
writeFileSync(cargoPath, cargo);

// tauri.conf.json
const tauriPath = join(root, "src-tauri/tauri.conf.json");
const tauri = JSON.parse(readFileSync(tauriPath, "utf8"));
tauri.version = version;
writeFileSync(tauriPath, JSON.stringify(tauri, null, 2) + "\n");

// README.md - update download link versions
const readmePath = join(root, "README.md");
let readme = readFileSync(readmePath, "utf8");
readme = readme.replace(
  /\/releases\/download\/v[\d.]+\/clippy[_-][\d.]+/g,
  (match) => match.replace(/[\d]+\.[\d]+\.[\d]+/g, version)
);
writeFileSync(readmePath, readme);

// Cargo.lock - update the clippy package version
const lockPath = join(root, "src-tauri/Cargo.lock");
let lock = readFileSync(lockPath, "utf8");
lock = lock.replace(
  /(name = "clippy"\nversion = )"[^"]*"/,
  `$1"${version}"`
);
writeFileSync(lockPath, lock);

// NSIS installer hooks
const hooksPath = join(root, "src-tauri/installer-hooks.nsh");
writeFileSync(
  hooksPath,
  `; Auto-generated by sync-version.js, do not edit manually
Caption "$(^Name) ${version}"
LangString ^SetupCaption \${LANG_ENGLISH} "Setup clippy ${version}"
LangString ^SetupCaption \${LANG_SIMPCHINESE} "安装 clippy ${version}"
LangString ^SetupCaption \${LANG_SPANISH} "Instalacion de clippy ${version}"
LangString ^SetupCaption \${LANG_FRENCH} "Installation de clippy ${version}"
LangString ^SetupCaption \${LANG_ARABIC} "تثبيت clippy ${version}"
LangString ^SetupCaption \${LANG_RUSSIAN} "Установка clippy ${version}"
LangString ^SetupCaption \${LANG_JAPANESE} "clippy ${version} セットアップ"
LangString ^SetupCaption \${LANG_GERMAN} "Setup von clippy ${version}"
LangString ^SetupCaption \${LANG_KOREAN} "clippy ${version} 설치"
LangString ^SetupCaption \${LANG_TURKISH} "clippy ${version} Kurulumu"
LangString ^SetupCaption \${LANG_ITALIAN} "Installazione di clippy ${version}"
LangString ^SetupCaption \${LANG_DUTCH} "Installatie van clippy ${version}"
LangString ^UninstallCaption \${LANG_ENGLISH} "Uninstall clippy ${version}"
LangString ^UninstallCaption \${LANG_SIMPCHINESE} "卸载 clippy ${version}"
LangString ^UninstallCaption \${LANG_SPANISH} "Desinstalar clippy ${version}"
LangString ^UninstallCaption \${LANG_FRENCH} "Desinstallation de clippy ${version}"
LangString ^UninstallCaption \${LANG_ARABIC} "إلغاء تثبيت clippy ${version}"
LangString ^UninstallCaption \${LANG_RUSSIAN} "Удаление clippy ${version}"
LangString ^UninstallCaption \${LANG_JAPANESE} "clippy ${version} アンインストール"
LangString ^UninstallCaption \${LANG_GERMAN} "Deinstallation von clippy ${version}"
LangString ^UninstallCaption \${LANG_KOREAN} "clippy ${version} 제거"
LangString ^UninstallCaption \${LANG_TURKISH} "clippy ${version} Kaldirma"
LangString ^UninstallCaption \${LANG_ITALIAN} "Disinstallazione di clippy ${version}"
LangString ^UninstallCaption \${LANG_DUTCH} "Verwijderen van clippy ${version}"
`
);

console.log(`Synced version ${version} to Cargo.toml, tauri.conf.json, Cargo.lock, README.md, installer-hooks.nsh`);
