[package]
name = "common"
version = "1.0.0"
edition = "2021"

[lib]
name = "common"
path = "src/lib.rs"

[dependencies]
entity = { path = "../entity" }
global-hotkey = "0"
sea-orm = { version = "1" }
serde = { version = "1" }
serde_json = { version = "1" }
