[package]
name = "common"
version = "1.0.0"
edition = "2021"

[lib]
name = "common"
path = "src/lib.rs"

[dependencies]
entity = { path = "../entity" }
google-drive3 = { version = "6.0.0" }
global-hotkey = "0"
sea-orm = "1"
serde = "1"
serde_json = "1"
tl = "0"
