//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::clipboard::Entity as Clipboard;
pub use super::clipboard_file::Entity as ClipboardFile;
pub use super::clipboard_html::Entity as ClipboardHtml;
pub use super::clipboard_image::Entity as ClipboardImage;
pub use super::clipboard_rtf::Entity as ClipboardRtf;
pub use super::clipboard_text::Entity as ClipboardText;
pub use super::hotkey::Entity as Hotkey;
pub use super::settings::Entity as Settings;
