[package]
name = "entity"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sea-orm = { version = "^0" }
chrono = "^0"
serde = "1.0.163"
serde_json = "1.0.96"
