name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'docs/**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Docker run
        run: cd docs && docker compose up -d --force-recreate --build