name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'docs/**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Create env file
        run: |
          touch .env
          echo TAURI_GOOGLE_CLIENT_ID=${{ secrets.TAURI_GOOGLE_CLIENT_ID }} > .env
          echo TAURI_GOOGLE_CLIENT_SECRET=${{ secrets.TAURI_GOOGLE_CLIENT_SECRET }} >> .env
          cat .env

      
      - name: Docker run
        run: cd docs && docker compose up -d --force-recreate --build